# Generated by Django 4.2.7 on 2023-11-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название праздника')),
                ('date_start', models.DateTimeField(null=True, verbose_name='дата начала события')),
                ('date_end', models.DateTimeField(null=True, verbose_name='дата окончания события')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='описание')),
                ('address', models.CharField(max_length=360, null=True, verbose_name='адрес')),
                ('background', models.ImageField(upload_to='events/')),
                ('dresscode', models.CharField(blank=True, default='Отсутствует', max_length=256, verbose_name='дресс код')),
            ],
            options={
                'verbose_name': 'праздник',
                'verbose_name_plural': 'праздники',
            },
        ),
        migrations.CreateModel(
            name='WebConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='config/', verbose_name='логотип')),
                ('site_name', models.CharField(max_length=256, verbose_name='название сайта')),
                ('pic_buy', models.ImageField(upload_to='config/', verbose_name='картинка для "я куплю"')),
                ('pic_bought', models.ImageField(upload_to='config/', verbose_name='картинка для "я купил"')),
                ('pic_arrow', models.ImageField(upload_to='config/', verbose_name='стрелка')),
                ('pic_new_gift', models.ImageField(upload_to='config/', verbose_name='картинка для "новый подарок"')),
            ],
            options={
                'verbose_name': 'настройку',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название подарка')),
                ('price', models.PositiveIntegerField(verbose_name='цена подарка')),
                ('photo', models.ImageField(upload_to='gifts/')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылка на подарок')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='core.event', verbose_name='праздник')),
            ],
            options={
                'verbose_name': 'подарок',
                'verbose_name_plural': 'подарки',
            },
        ),
    ]
